### ISSUE TITLE
SSML tags support

### ISSUE THREAD

**Issue by DrinkSlurp** [aws-samples/amazon-polly-metahumans#23]
Hi, I have been digging on the [AWS Polly docs](https://docs.aws.amazon.com/es_es/polly/latest/dg/ssml-to-speech-console.html) and see that the command CLI accepts SSML tags. While I can produce audio file that follow these tags with the CLI, I cannot make it work in UE4. 

When I pass a text with such tags (between tag symbols), the metahuman simply speaks the tag as if it is normal text.

Is there any way for Polly CLI to accept these tags from UE?

Thanks!

**Comment by DrinkSlurp** [comment]
Hello, 
I keep testing this feature and, although it works when requested from the command CLI, it does not from the blueprints.
Any ideas about this?

**Comment by Krxtopher** [comment]
@DrinkSlurp I don't have the project downloaded at the moment to test the exact syntax, but here is a general description of the changes you'll need to make in order to use SSML.

Open the `Source/AmazonPollyMetaHuman/Private/SpeechComponent.cpp` file for editing.

You'll want to edit the `CreatePollyAudioRequest()` function defined starting at line 160. Inside that function it sets a few properties on the `PollyRequest` object. You'll need to set one more. It will look something like this...

```
PollyRequest.SetTextType(Aws::Polly::Model::TextType::ssml);
```

That should be it. If you need more details on how the Polly C++ API works check the documentation for the [**PollyClient** class found here](https://sdk.amazonaws.com/cpp/api/LATEST/class_aws_1_1_polly_1_1_polly_client.html).

**Comment by DrinkSlurp** [comment]
Sorry! My fault!
I was using it for Spanish voice and it looks like some tags are not accepted in every language or voice type.
Thanks!
