### ISSUE TITLE
How to extend this project to different languages?

### ISSUE THREAD

**Issue by luopeixiang** [aws-samples/amazon-polly-metahumans#5]
This is an amazing demo. I would like to ask how should I modify the code to make the demo support different languages like Chinese?

**Comment by cwalkere** [comment]
I'm not sure how well the the animation visemes would match up when using Mandarin since the visemes were created with English in mind, but you can experiment by adding the language you'd like to these files: 

https://github.com/aws-samples/amazon-polly-metahumans/blob/main/Source/AmazonPollyMetaHuman/Public/VoiceId.h
https://github.com/aws-samples/amazon-polly-metahumans/blob/main/Source/AmazonPollyMetaHuman/Private/VoiceId.cpp

then recompe, then go into the unreal editor and go to the Ada blueprint (https://github.com/aws-samples/amazon-polly-metahumans/blob/main/Content/AmazonPollyMetaHuman/Ada/BP_Ada.uasset) and find where the voice id is being set and changing that from the current voice ID to the new one you added in the dropdown. Recompile again and it should then speak in that different language.
